#version 450
#extension GL_ARB_separate_shader_objects : enable

#define WORKGROUP_SIZE 16

layout (local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

layout( push_constant ) uniform constants
{
    int mInvocationCount;
} PushConstants;

layout (std430, set = 0, binding = 1) writeonly buffer OutVertexData {
    vec3[] vertices;
};

void main()
{
    if( gl_GlobalInvocationID.x >= PushConstants.mInvocationCount ) return;
}
